from dataclasses import dataclass


BATCH_SIZE = 8

IMG_C = 1
IMG_H = 28
IMG_W = 28

KERNEL_SIZE = 3
STRIDE = 2
PADDING = 1

C1 = 4
C2 = 8
C3 = 16

N_CLASSES = 10


def conv_out_size(size: int) -> int:
    return ((size + 2 * PADDING - KERNEL_SIZE) // STRIDE) + 1


CONV1_OUT_H = conv_out_size(IMG_H)
CONV1_OUT_W = conv_out_size(IMG_W)
CONV2_OUT_H = conv_out_size(CONV1_OUT_H)
CONV2_OUT_W = conv_out_size(CONV1_OUT_W)
CONV3_OUT_H = conv_out_size(CONV2_OUT_H)
CONV3_OUT_W = conv_out_size(CONV2_OUT_W)

assert (CONV1_OUT_H, CONV1_OUT_W) == (14, 14)
assert (CONV2_OUT_H, CONV2_OUT_W) == (7, 7)
assert (CONV3_OUT_H, CONV3_OUT_W) == (4, 4)

IMG_ELEMS = BATCH_SIZE * IMG_H * IMG_W * IMG_C
ACT1_ELEMS = BATCH_SIZE * CONV1_OUT_H * CONV1_OUT_W * C1
ACT2_ELEMS = BATCH_SIZE * CONV2_OUT_H * CONV2_OUT_W * C2
ACT3_ELEMS = BATCH_SIZE * CONV3_OUT_H * CONV3_OUT_W * C3
POOLED_ELEMS = BATCH_SIZE * C3

CONV1_W_ELEMS = C1 * IMG_C * KERNEL_SIZE * KERNEL_SIZE
CONV2_W_ELEMS = C2 * C1 * KERNEL_SIZE * KERNEL_SIZE
CONV3_W_ELEMS = C3 * C2 * KERNEL_SIZE * KERNEL_SIZE
HEAD_W_ELEMS = C3 * N_CLASSES
TOTAL_WEIGHT_ELEMS = CONV1_W_ELEMS + CONV2_W_ELEMS + CONV3_W_ELEMS + HEAD_W_ELEMS

CONV1_CKPT_ELEMS = IMG_ELEMS + ACT1_ELEMS
CONV2_CKPT_ELEMS = ACT1_ELEMS + ACT2_ELEMS
CONV3_CKPT_ELEMS = ACT2_ELEMS + ACT3_ELEMS

LABELS_IO_ELEMS = 2 * BATCH_SIZE


@dataclass(frozen=True)
class WeightOffsets:
    conv1: int = 0
    conv2: int = CONV1_W_ELEMS
    conv3: int = CONV1_W_ELEMS + CONV2_W_ELEMS
    head: int = CONV1_W_ELEMS + CONV2_W_ELEMS + CONV3_W_ELEMS


WEIGHT_OFFSETS = WeightOffsets()
